/**
 * @type {Object.<string, (string | string[])[]>}
 */
const strokeExpansionRules = {
    // SYMBOL : CAN BE RETRIEVED BY ...
    // string as value -> choice of resolution
    // string[] as value -> expansion
    'H' : ['H'],
    'I' : ['I'],
    'V1': ['V'],
    'V2': ['V'],
    'R1': ['R'],
    'R2': ['R', 'H'],
    'R3': ['R', 'I'],
    'R4': ['R', 'V1'],
    'R5': ['R', 'V2'],
    'O' : ['O'],
    'Q' : ['Q'],
    'P' : ['P'],

    'D1': ['D'],
    'D2': ['D', ['H', 'H', 'I']],
    'C1': ['C'],
    'C2': ['C', ['H', 'H', 'I']],
    'A' : ['A'],
    'U1': ['U'],
    'U2': ['U'],
    'U3': ['U'],
    'S' : ['S'],

    'EL2': ['E', ['D1', 'D1']],
    'ER2': ['E', ['C1', 'C1']],
    'ET2': ['E', ['U1', 'U1']],
    'EB2': ['E', ['A', 'A']],
    'EL3': ['E', ['D1', 'D1', 'D1']],
    'ER3': ['E', ['C1', 'C1', 'C1']],
    'ET3': ['E', ['U1', 'U1', 'U1']],
    'EB3': ['E', ['A', 'A', 'A']],


    'J1': ['J', ['I', 'V2']],
    'J2': ['J'],
    'L1': ['L', ['I', 'V1']],
    'L2': ['L'],
    'F' : ['F', ['I', 'V2']],
    'Z' : ['Z', ['I', 'V2', 'V2']],
    'N1': ['N', ['I', 'I', 'V2']],
    'N2': ['N', ['I', 'V2', 'V2']],
    'M1': ['M', ['I', 'I', 'V2', 'V2']],
    'M2': ['M', ['I', 'I', 'V2', 'V2']],
    'M3': ['M', ['V1','V1', 'V2', 'V2']],

    'G1': ['G', ['I', 'C']],
    'G2': ['G', ['I', 'D']],
    'G3': ['G', ['I', 'I', 'I', 'V1', 'V2']],

    'X' : ['X', ['V1', 'V2']],
    'T' : ['T', ['H', 'I']],
    'K1': ['K', ['I', 'V1', 'V2']],
    'K2': ['K', ['H', 'V1', 'V2']],
    'B1': ['B', ['I', 'I', 'V1', 'V2']],
    'B2': ['B', ['H', 'H', 'V1', 'V2']],
    'B3': ['B', ['H', 'H', 'V1', 'V2']],
};

/**
 * 
 * @param {string[]} arr
 * @returns {Object.<string, number>} 
 */
function arrToCountObj(arr) {
    const result = {};
    for (const s of arr) {
        result[s] = (result[s] || 0) + 1;
    }
    return result;
}

/**
 * @type {Object.<string, Object<string, number>[]>}
 */
const strokeExpansionRulesCleaned = Object.fromEntries(
    Object.entries(strokeExpansionRules)
        .filter(([k, v]) => v.length > 1 || k[0] != v[0])
        // remove identity mappings
        .map(([k, v]) => [k, v
            .map(x => typeof x === 'string' ? [x] : x)
            // turn string into string[]
            .map(arr => arrToCountObj(arr))
            // turn string[] into <string, number>
        ]) 
);

const inputtableStrokes = new Set(Object.values(strokeExpansionRules)
    .map(arr => arr.flat()).flat()
    .filter(elem => !strokeExpansionRules[elem] ||
        // VALUES THAT DO NOT APPEAR AS KEYS, OR
        strokeExpansionRules[elem].includes(elem)
        // VALUES IN IDENTITY MAPPINGS
));

function expandStrokes(strokes, memo) {
    const key = JSON.stringify(Object.entries(strokes).sort());
    if (memo.has(key)) return memo.get(key);
    
    const sym = Object.keys(strokes).find(s => s in strokeExpansionRulesCleaned);
    if (!sym) {
        return [strokes];
    }
    
    const total = strokes[sym];
    const variants = strokeExpansionRulesCleaned[sym];
    const results = [];
    
    let hasIdentity = false;
    const realVariants = [];
    for (const v of variants) {
        if (Object.keys(v).length === 1 && v[sym] === 1) {
            hasIdentity = true;
        } else {
            realVariants.push(v);
        }
    }
    
    if (realVariants.length === 0) {
        const out = [strokes];
        memo.set(key, out);
        return out;
    }
    
    function allocate(remain, idx, distribution) {
        if (idx === realVariants.length - 1) {
            distribution.push(remain);
            
            const next = { ...strokes };
            delete next[sym];
            
            for (let i = 0; i < realVariants.length; i++) {
                const times = distribution[i];
                if (times === 0) continue;
                const v = realVariants[i];
                for (const [s, c] of Object.entries(v)) {
                    next[s] = (next[s] || 0) + c * times;
                }
            }
            
            for (const sub of expandStrokes(next, memo)) {
                results.push(sub);
            }
            
            distribution.pop();
            return;
        }
        
        for (let i = 0; i <= remain; i++) {
            distribution.push(i);
            allocate(remain - i, idx + 1, distribution);
            distribution.pop();
        }
    }
    
    allocate(total, 0, []);
    
    if (hasIdentity) {
        results.push(strokes);
    }
    
    const unique = new Map();
    for (const r of results) {
        const k = JSON.stringify(Object.entries(r).sort());
        if (!unique.has(k)) unique.set(k, r);
    }
    const out = Array.from(unique.values());
    
    memo.set(key, out);
    return out;
}

const charStrokes = {
    "ꀀ": ['U1','H','H'],
    "ꀁ": ['U1','H','D1','A'],
    "ꀂ": ['U1','H','D1'],
    "ꀃ": ['C1','I','D1','V2'],
    "ꀄ": ['O','U1','H'],
    "ꀅ": ['O','F','J1','A'],
    "ꀆ": ['O','F','J1'],
    "ꀇ": ['O','C1','I','I'],
    "ꀈ": ['N1','V2'],
    "ꀉ": ['Z','V2','I','A'],
    "ꀊ": ['Z','V2','I'],
    "ꀋ": ['Z','V2','C1'],
    "ꀌ": ['H','I','I','I','I','A'],
    "ꀍ": ['H','I','I','I','I'],
    "ꀎ": ['O','O','U1'],
    "ꀏ": ['O','I','ER2'],
    "ꀐ": ['Z','O','R3','A'],
    "ꀑ": ['Z','O','R3'],
    "ꀒ": ['Z','O'],
    "ꀓ": ['EL3','H','Z','A'],
    "ꀔ": ['EL3','H','Z'],
    "ꀕ": ['ET2','R3','R3'],
    "ꀖ": ['O','X'],
    "ꀗ": ['I','H','C1','A'],
    "ꀘ": ['I','H','C1'],
    "ꀙ": ['N1','H','C1'],
    "ꀚ": ['O','H','C1'],
    "ꀛ": ['O','V1','A'],
    "ꀜ": ['O','V1'],
    "ꀝ": ['O','EL2'],
    "ꀞ": ['O','I','I','H'],
    "ꀟ": ['ET2','I','I','H','A'],
    "ꀠ": ['ET2','I','I','H'],
    "ꀡ": ['V1','V2','I','I','H'],
    "ꀢ": ['G2','H','H','I','A'],
    "ꀣ": ['G2','H','H','I'],
    "ꀤ": ['H','H','I'],
    "ꀥ": ['C1','ER2','V2','V1'],
    "ꀦ": ['O','H','I','H','A'],
    "ꀧ": ['O','H','I','H'],
    "ꀨ": ['H','H','H','H','I','I'],
    "ꀩ": ['EB2','U1','R3','A'],
    "ꀪ": ['EB2','U1','R3'],
    "ꀫ": ['H','I','H','X'],
    "ꀬ": ['O','I','R3'],
    "ꀭ": ['J1','I','A'],
    "ꀮ": ['J1','I'],
    "ꀯ": ['C1','C1'],
    "ꀰ": ['U2','H','H','A'],
    "ꀱ": ['U2','H','H'],
    "ꀲ": ['Z','X'],
    "ꀳ": ['Z','M3','A'],
    "ꀴ": ['Z','M3'],
    "ꀵ": ['F','H','F','U1'],
    "ꀶ": ['C1','I','R3','R3','R3','R3','F','A'],
    "ꀷ": ['C1','I','R3','R3','R3','R3','F'],
    "ꀸ": ['C1','F','H','H'],
    "ꀹ": ['O','L1','A'],
    "ꀺ": ['O','L1'],
    "ꀻ": ['X','R3','R3'],
    "ꀼ": ['O','H','R3','R3','A'],
    "ꀽ": ['O','H','R3','R3'],
    "ꀾ": ['O','R3','ET2'],
    "ꀿ": ['I','I','H'],
    "ꁀ": ['U1','I','H','A'],
    "ꁁ": ['U1','I','H'],
    "ꁂ": ['U1','H','I'],
    "ꁃ": ['C1','H','I','R3','R3','R3','A'],
    "ꁄ": ['C1','H','I','R3','R3','R3'],
    "ꁅ": ['C1','H','I','J2'],
    "ꁆ": ['O','H','H','EL2'],
    "ꁇ": ['U1','I','H','H','A'],
    "ꁈ": ['U1','I','H','H'],
    "ꁉ": ['C1','H','H','H','I'],
    "ꁊ": ['G3'],
    "ꁋ": ['ER3','I','A'],
    "ꁌ": ['ER3','I'],
    "ꁍ": ['Z','C1','R3'],
    "ꁎ": ['O','R3','H','R3','R3','A'],
    "ꁏ": ['O','R3','H','R3','R3'],
    "ꁐ": ['C1','F'],
    "ꁑ": ['B1','R3','A'],
    "ꁒ": ['B1','R3'],
    "ꁓ": ['F','F','H','I','U1'],
    "ꁔ": ['F','R3','R3','C1','A'],
    "ꁕ": ['F','R3','R3','C1'],
    "ꁖ": ['O','H','H','ET2'],
    "ꁗ": ['X','I','A'],
    "ꁘ": ['X','I'],
    "ꁙ": ['O','C1','D1'],
    "ꁚ": ['O','ET2','R3'],
    "ꁛ": ['Z','C1','C1','H','A'],
    "ꁜ": ['Z','C1','C1','H'],
    "ꁝ": ['D1','C1','H'],
    "ꁞ": ['D1','C1','H','H','H'],
    "ꁟ": ['K1','K1','A'],
    "ꁠ": ['K1','K1'],
    "ꁡ": ['ET2','H','H'],
    "ꁢ": ['J1','N1','H','H','A'],
    "ꁣ": ['J1','N1','H','H'],
    "ꁤ": ['O','R3','R3','R3','R3'],
    "ꁥ": [],
    "ꁦ": [],
    "ꁧ": [],
    "ꁨ": [],
    "ꁩ": [],
    "ꁪ": [],
    "ꁫ": [],
    "ꁬ": [],
    "ꁭ": [],
    "ꁮ": [],
    "ꁯ": [],
    "ꁰ": [],
    "ꁱ": [],
    "ꁲ": [],
    "ꁳ": [],
    "ꁴ": [],
    "ꁵ": [],
    "ꁶ": [],
    "ꁷ": [],
    "ꁸ": [],
    "ꁹ": [],
    "ꁺ": [],
    "ꁻ": [],
    "ꁼ": [],
    "ꁽ": [],
    "ꁾ": [],
    "ꁿ": [],
    "ꂀ": [],
    "ꂁ": [],
    "ꂂ": [],
    "ꂃ": [],
    "ꂄ": [],
    "ꂅ": [],
    "ꂆ": [],
    "ꂇ": [],
    "ꂈ": [],
    "ꂉ": [],
    "ꂊ": [],
    "ꂋ": [],
    "ꂌ": [],
    "ꂍ": [],
    "ꂎ": [],
    "ꂏ": [],
    "ꂐ": [],
    "ꂑ": [],
    "ꂒ": [],
    "ꂓ": [],
    "ꂔ": [],
    "ꂕ": [],
    "ꂖ": [],
    "ꂗ": [],
    "ꂘ": [],
    "ꂙ": [],
    "ꂚ": [],
    "ꂛ": [],
    "ꂜ": [],
    "ꂝ": [],
    "ꂞ": [],
    "ꂟ": [],
    "ꂠ": [],
    "ꂡ": [],
    "ꂢ": [],
    "ꂣ": [],
    "ꂤ": [],
    "ꂥ": [],
    "ꂦ": [],
    "ꂧ": [],
    "ꂨ": [],
    "ꂩ": [],
    "ꂪ": [],
    "ꂫ": [],
    "ꂬ": [],
    "ꂭ": [],
    "ꂮ": [],
    "ꂯ": [],
    "ꂰ": [],
    "ꂱ": [],
    "ꂲ": [],
    "ꂳ": [],
    "ꂴ": [],
    "ꂵ": [],
    "ꂶ": [],
    "ꂷ": [],
    "ꂸ": [],
    "ꂹ": [],
    "ꂺ": [],
    "ꂻ": [],
    "ꂼ": [],
    "ꂽ": [],
    "ꂾ": [],
    "ꂿ": [],
    "ꃀ": [],
    "ꃁ": [],
    "ꃂ": [],
    "ꃃ": [],
    "ꃄ": [],
    "ꃅ": [],
    "ꃆ": [],
    "ꃇ": [],
    "ꃈ": [],
    "ꃉ": [],
    "ꃊ": [],
    "ꃋ": [],
    "ꃌ": [],
    "ꃍ": [],
    "ꃎ": [],
    "ꃏ": [],
    "ꃐ": [],
    "ꃑ": [],
    "ꃒ": [],
    "ꃓ": [],
    "ꃔ": [],
    "ꃕ": [],
    "ꃖ": [],
    "ꃗ": [],
    "ꃘ": [],
    "ꃙ": [],
    "ꃚ": [],
    "ꃛ": [],
    "ꃜ": [],
    "ꃝ": [],
    "ꃞ": [],
    "ꃟ": [],
    "ꃠ": [],
    "ꃡ": [],
    "ꃢ": [],
    "ꃣ": [],
    "ꃤ": [],
    "ꃥ": [],
    "ꃦ": [],
    "ꃧ": [],
    "ꃨ": [],
    "ꃩ": [],
    "ꃪ": [],
    "ꃫ": [],
    "ꃬ": [],
    "ꃭ": [],
    "ꃮ": [],
    "ꃯ": [],
    "ꃰ": [],
    "ꃱ": [],
    "ꃲ": [],
    "ꃳ": [],
    "ꃴ": [],
    "ꃵ": [],
    "ꃶ": [],
    "ꃷ": [],
    "ꃸ": [],
    "ꃹ": [],
    "ꃺ": [],
    "ꃻ": [],
    "ꃼ": [],
    "ꃽ": [],
    "ꃾ": [],
    "ꃿ": [],
    "ꄀ": [],
    "ꄁ": [],
    "ꄂ": [],
    "ꄃ": [],
    "ꄄ": [],
    "ꄅ": [],
    "ꄆ": [],
    "ꄇ": [],
    "ꄈ": [],
    "ꄉ": [],
    "ꄊ": [],
    "ꄋ": [],
    "ꄌ": [],
    "ꄍ": [],
    "ꄎ": [],
    "ꄏ": [],
    "ꄐ": [],
    "ꄑ": [],
    "ꄒ": [],
    "ꄓ": [],
    "ꄔ": [],
    "ꄕ": [],
    "ꄖ": [],
    "ꄗ": [],
    "ꄘ": [],
    "ꄙ": [],
    "ꄚ": [],
    "ꄛ": [],
    "ꄜ": [],
    "ꄝ": [],
    "ꄞ": [],
    "ꄟ": [],
    "ꄠ": [],
    "ꄡ": [],
    "ꄢ": [],
    "ꄣ": [],
    "ꄤ": [],
    "ꄥ": [],
    "ꄦ": [],
    "ꄧ": [],
    "ꄨ": [],
    "ꄩ": [],
    "ꄪ": [],
    "ꄫ": [],
    "ꄬ": [],
    "ꄭ": [],
    "ꄮ": [],
    "ꄯ": [],
    "ꄰ": [],
    "ꄱ": [],
    "ꄲ": [],
    "ꄳ": [],
    "ꄴ": [],
    "ꄵ": [],
    "ꄶ": [],
    "ꄷ": [],
    "ꄸ": [],
    "ꄹ": [],
    "ꄺ": [],
    "ꄻ": [],
    "ꄼ": [],
    "ꄽ": [],
    "ꄾ": [],
    "ꄿ": [],
    "ꅀ": [],
    "ꅁ": [],
    "ꅂ": [],
    "ꅃ": [],
    "ꅄ": [],
    "ꅅ": [],
    "ꅆ": [],
    "ꅇ": [],
    "ꅈ": [],
    "ꅉ": [],
    "ꅊ": [],
    "ꅋ": [],
    "ꅌ": [],
    "ꅍ": [],
    "ꅎ": [],
    "ꅏ": [],
    "ꅐ": [],
    "ꅑ": [],
    "ꅒ": [],
    "ꅓ": [],
    "ꅔ": [],
    "ꅕ": [],
    "ꅖ": [],
    "ꅗ": [],
    "ꅘ": [],
    "ꅙ": [],
    "ꅚ": [],
    "ꅛ": [],
    "ꅜ": [],
    "ꅝ": [],
    "ꅞ": [],
    "ꅟ": [],
    "ꅠ": [],
    "ꅡ": [],
    "ꅢ": [],
    "ꅣ": [],
    "ꅤ": [],
    "ꅥ": [],
    "ꅦ": [],
    "ꅧ": [],
    "ꅨ": [],
    "ꅩ": [],
    "ꅪ": [],
    "ꅫ": [],
    "ꅬ": [],
    "ꅭ": [],
    "ꅮ": [],
    "ꅯ": [],
    "ꅰ": [],
    "ꅱ": [],
    "ꅲ": [],
    "ꅳ": [],
    "ꅴ": [],
    "ꅵ": [],
    "ꅶ": [],
    "ꅷ": [],
    "ꅸ": [],
    "ꅹ": [],
    "ꅺ": [],
    "ꅻ": [],
    "ꅼ": [],
    "ꅽ": [],
    "ꅾ": [],
    "ꅿ": [],
    "ꆀ": [],
    "ꆁ": [],
    "ꆂ": [],
    "ꆃ": [],
    "ꆄ": [],
    "ꆅ": [],
    "ꆆ": [],
    "ꆇ": [],
    "ꆈ": [],
    "ꆉ": [],
    "ꆊ": [],
    "ꆋ": [],
    "ꆌ": [],
    "ꆍ": [],
    "ꆎ": [],
    "ꆏ": [],
    "ꆐ": [],
    "ꆑ": [],
    "ꆒ": [],
    "ꆓ": [],
    "ꆔ": [],
    "ꆕ": [],
    "ꆖ": [],
    "ꆗ": [],
    "ꆘ": [],
    "ꆙ": [],
    "ꆚ": [],
    "ꆛ": [],
    "ꆜ": [],
    "ꆝ": [],
    "ꆞ": [],
    "ꆟ": [],
    "ꆠ": [],
    "ꆡ": [],
    "ꆢ": [],
    "ꆣ": [],
    "ꆤ": [],
    "ꆥ": [],
    "ꆦ": [],
    "ꆧ": [],
    "ꆨ": [],
    "ꆩ": [],
    "ꆪ": [],
    "ꆫ": [],
    "ꆬ": [],
    "ꆭ": [],
    "ꆮ": [],
    "ꆯ": [],
    "ꆰ": [],
    "ꆱ": [],
    "ꆲ": [],
    "ꆳ": [],
    "ꆴ": [],
    "ꆵ": [],
    "ꆶ": [],
    "ꆷ": [],
    "ꆸ": [],
    "ꆹ": [],
    "ꆺ": [],
    "ꆻ": [],
    "ꆼ": [],
    "ꆽ": [],
    "ꆾ": [],
    "ꆿ": [],
    "ꇀ": [],
    "ꇁ": [],
    "ꇂ": [],
    "ꇃ": [],
    "ꇄ": [],
    "ꇅ": [],
    "ꇆ": [],
    "ꇇ": [],
    "ꇈ": [],
    "ꇉ": [],
    "ꇊ": [],
    "ꇋ": [],
    "ꇌ": [],
    "ꇍ": [],
    "ꇎ": [],
    "ꇏ": [],
    "ꇐ": [],
    "ꇑ": [],
    "ꇒ": [],
    "ꇓ": [],
    "ꇔ": [],
    "ꇕ": [],
    "ꇖ": [],
    "ꇗ": [],
    "ꇘ": [],
    "ꇙ": [],
    "ꇚ": [],
    "ꇛ": [],
    "ꇜ": [],
    "ꇝ": [],
    "ꇞ": [],
    "ꇟ": [],
    "ꇠ": [],
    "ꇡ": [],
    "ꇢ": [],
    "ꇣ": [],
    "ꇤ": [],
    "ꇥ": [],
    "ꇦ": [],
    "ꇧ": [],
    "ꇨ": [],
    "ꇩ": [],
    "ꇪ": [],
    "ꇫ": [],
    "ꇬ": [],
    "ꇭ": [],
    "ꇮ": [],
    "ꇯ": [],
    "ꇰ": [],
    "ꇱ": [],
    "ꇲ": [],
    "ꇳ": [],
    "ꇴ": [],
    "ꇵ": [],
    "ꇶ": [],
    "ꇷ": [],
    "ꇸ": [],
    "ꇹ": [],
    "ꇺ": [],
    "ꇻ": [],
    "ꇼ": [],
    "ꇽ": [],
    "ꇾ": [],
    "ꇿ": [],
    "ꈀ": [],
    "ꈁ": [],
    "ꈂ": [],
    "ꈃ": [],
    "ꈄ": [],
    "ꈅ": [],
    "ꈆ": [],
    "ꈇ": [],
    "ꈈ": [],
    "ꈉ": [],
    "ꈊ": [],
    "ꈋ": [],
    "ꈌ": [],
    "ꈍ": [],
    "ꈎ": [],
    "ꈏ": [],
    "ꈐ": [],
    "ꈑ": [],
    "ꈒ": [],
    "ꈓ": [],
    "ꈔ": [],
    "ꈕ": [],
    "ꈖ": [],
    "ꈗ": [],
    "ꈘ": [],
    "ꈙ": [],
    "ꈚ": [],
    "ꈛ": [],
    "ꈜ": [],
    "ꈝ": [],
    "ꈞ": [],
    "ꈟ": [],
    "ꈠ": [],
    "ꈡ": [],
    "ꈢ": [],
    "ꈣ": [],
    "ꈤ": [],
    "ꈥ": [],
    "ꈦ": [],
    "ꈧ": [],
    "ꈨ": [],
    "ꈩ": [],
    "ꈪ": [],
    "ꈫ": [],
    "ꈬ": [],
    "ꈭ": [],
    "ꈮ": [],
    "ꈯ": [],
    "ꈰ": [],
    "ꈱ": [],
    "ꈲ": [],
    "ꈳ": [],
    "ꈴ": [],
    "ꈵ": [],
    "ꈶ": [],
    "ꈷ": [],
    "ꈸ": [],
    "ꈹ": [],
    "ꈺ": [],
    "ꈻ": [],
    "ꈼ": [],
    "ꈽ": [],
    "ꈾ": [],
    "ꈿ": [],
    "ꉀ": [],
    "ꉁ": [],
    "ꉂ": [],
    "ꉃ": [],
    "ꉄ": [],
    "ꉅ": [],
    "ꉆ": [],
    "ꉇ": [],
    "ꉈ": [],
    "ꉉ": [],
    "ꉊ": [],
    "ꉋ": [],
    "ꉌ": [],
    "ꉍ": [],
    "ꉎ": [],
    "ꉏ": [],
    "ꉐ": [],
    "ꉑ": [],
    "ꉒ": [],
    "ꉓ": [],
    "ꉔ": [],
    "ꉕ": [],
    "ꉖ": [],
    "ꉗ": [],
    "ꉘ": [],
    "ꉙ": [],
    "ꉚ": [],
    "ꉛ": [],
    "ꉜ": [],
    "ꉝ": [],
    "ꉞ": [],
    "ꉟ": [],
    "ꉠ": [],
    "ꉡ": [],
    "ꉢ": [],
    "ꉣ": [],
    "ꉤ": [],
    "ꉥ": [],
    "ꉦ": [],
    "ꉧ": [],
    "ꉨ": [],
    "ꉩ": [],
    "ꉪ": [],
    "ꉫ": [],
    "ꉬ": [],
    "ꉭ": [],
    "ꉮ": [],
    "ꉯ": [],
    "ꉰ": [],
    "ꉱ": [],
    "ꉲ": [],
    "ꉳ": [],
    "ꉴ": [],
    "ꉵ": [],
    "ꉶ": [],
    "ꉷ": [],
    "ꉸ": [],
    "ꉹ": [],
    "ꉺ": [],
    "ꉻ": [],
    "ꉼ": [],
    "ꉽ": [],
    "ꉾ": [],
    "ꉿ": [],
    "ꊀ": [],
    "ꊁ": [],
    "ꊂ": [],
    "ꊃ": [],
    "ꊄ": [],
    "ꊅ": [],
    "ꊆ": [],
    "ꊇ": [],
    "ꊈ": [],
    "ꊉ": [],
    "ꊊ": [],
    "ꊋ": [],
    "ꊌ": [],
    "ꊍ": [],
    "ꊎ": [],
    "ꊏ": [],
    "ꊐ": [],
    "ꊑ": [],
    "ꊒ": [],
    "ꊓ": [],
    "ꊔ": [],
    "ꊕ": [],
    "ꊖ": [],
    "ꊗ": [],
    "ꊘ": [],
    "ꊙ": [],
    "ꊚ": [],
    "ꊛ": [],
    "ꊜ": [],
    "ꊝ": [],
    "ꊞ": [],
    "ꊟ": [],
    "ꊠ": [],
    "ꊡ": [],
    "ꊢ": [],
    "ꊣ": [],
    "ꊤ": [],
    "ꊥ": [],
    "ꊦ": [],
    "ꊧ": [],
    "ꊨ": [],
    "ꊩ": [],
    "ꊪ": [],
    "ꊫ": [],
    "ꊬ": [],
    "ꊭ": [],
    "ꊮ": [],
    "ꊯ": [],
    "ꊰ": [],
    "ꊱ": [],
    "ꊲ": [],
    "ꊳ": [],
    "ꊴ": [],
    "ꊵ": [],
    "ꊶ": [],
    "ꊷ": [],
    "ꊸ": [],
    "ꊹ": [],
    "ꊺ": [],
    "ꊻ": [],
    "ꊼ": [],
    "ꊽ": [],
    "ꊾ": [],
    "ꊿ": [],
    "ꋀ": [],
    "ꋁ": [],
    "ꋂ": [],
    "ꋃ": [],
    "ꋄ": [],
    "ꋅ": [],
    "ꋆ": [],
    "ꋇ": [],
    "ꋈ": [],
    "ꋉ": [],
    "ꋊ": [],
    "ꋋ": [],
    "ꋌ": [],
    "ꋍ": [],
    "ꋎ": [],
    "ꋏ": [],
    "ꋐ": [],
    "ꋑ": [],
    "ꋒ": [],
    "ꋓ": [],
    "ꋔ": [],
    "ꋕ": [],
    "ꋖ": [],
    "ꋗ": [],
    "ꋘ": [],
    "ꋙ": [],
    "ꋚ": [],
    "ꋛ": [],
    "ꋜ": [],
    "ꋝ": [],
    "ꋞ": [],
    "ꋟ": [],
    "ꋠ": [],
    "ꋡ": [],
    "ꋢ": [],
    "ꋣ": [],
    "ꋤ": [],
    "ꋥ": [],
    "ꋦ": [],
    "ꋧ": [],
    "ꋨ": [],
    "ꋩ": [],
    "ꋪ": [],
    "ꋫ": [],
    "ꋬ": [],
    "ꋭ": [],
    "ꋮ": [],
    "ꋯ": [],
    "ꋰ": [],
    "ꋱ": [],
    "ꋲ": [],
    "ꋳ": [],
    "ꋴ": [],
    "ꋵ": [],
    "ꋶ": [],
    "ꋷ": [],
    "ꋸ": [],
    "ꋹ": [],
    "ꋺ": [],
    "ꋻ": [],
    "ꋼ": [],
    "ꋽ": [],
    "ꋾ": [],
    "ꋿ": [],
    "ꌀ": [],
    "ꌁ": [],
    "ꌂ": [],
    "ꌃ": [],
    "ꌄ": [],
    "ꌅ": [],
    "ꌆ": [],
    "ꌇ": [],
    "ꌈ": [],
    "ꌉ": [],
    "ꌊ": [],
    "ꌋ": [],
    "ꌌ": [],
    "ꌍ": [],
    "ꌎ": [],
    "ꌏ": [],
    "ꌐ": [],
    "ꌑ": [],
    "ꌒ": [],
    "ꌓ": [],
    "ꌔ": [],
    "ꌕ": [],
    "ꌖ": [],
    "ꌗ": [],
    "ꌘ": [],
    "ꌙ": [],
    "ꌚ": [],
    "ꌛ": [],
    "ꌜ": [],
    "ꌝ": [],
    "ꌞ": [],
    "ꌟ": [],
    "ꌠ": [],
    "ꌡ": [],
    "ꌢ": [],
    "ꌣ": [],
    "ꌤ": [],
    "ꌥ": [],
    "ꌦ": [],
    "ꌧ": [],
    "ꌨ": [],
    "ꌩ": [],
    "ꌪ": [],
    "ꌫ": [],
    "ꌬ": [],
    "ꌭ": [],
    "ꌮ": [],
    "ꌯ": [],
    "ꌰ": [],
    "ꌱ": [],
    "ꌲ": [],
    "ꌳ": [],
    "ꌴ": [],
    "ꌵ": [],
    "ꌶ": [],
    "ꌷ": [],
    "ꌸ": [],
    "ꌹ": [],
    "ꌺ": [],
    "ꌻ": [],
    "ꌼ": [],
    "ꌽ": [],
    "ꌾ": [],
    "ꌿ": [],
    "ꍀ": [],
    "ꍁ": [],
    "ꍂ": [],
    "ꍃ": [],
    "ꍄ": [],
    "ꍅ": [],
    "ꍆ": [],
    "ꍇ": [],
    "ꍈ": [],
    "ꍉ": [],
    "ꍊ": [],
    "ꍋ": [],
    "ꍌ": [],
    "ꍍ": [],
    "ꍎ": [],
    "ꍏ": [],
    "ꍐ": [],
    "ꍑ": [],
    "ꍒ": [],
    "ꍓ": [],
    "ꍔ": [],
    "ꍕ": [],
    "ꍖ": [],
    "ꍗ": [],
    "ꍘ": [],
    "ꍙ": [],
    "ꍚ": [],
    "ꍛ": [],
    "ꍜ": [],
    "ꍝ": [],
    "ꍞ": [],
    "ꍟ": [],
    "ꍠ": [],
    "ꍡ": [],
    "ꍢ": [],
    "ꍣ": [],
    "ꍤ": [],
    "ꍥ": [],
    "ꍦ": [],
    "ꍧ": [],
    "ꍨ": [],
    "ꍩ": [],
    "ꍪ": [],
    "ꍫ": [],
    "ꍬ": [],
    "ꍭ": [],
    "ꍮ": [],
    "ꍯ": [],
    "ꍰ": [],
    "ꍱ": [],
    "ꍲ": [],
    "ꍳ": [],
    "ꍴ": [],
    "ꍵ": [],
    "ꍶ": [],
    "ꍷ": [],
    "ꍸ": [],
    "ꍹ": [],
    "ꍺ": [],
    "ꍻ": [],
    "ꍼ": [],
    "ꍽ": [],
    "ꍾ": [],
    "ꍿ": [],
    "ꎀ": [],
    "ꎁ": [],
    "ꎂ": [],
    "ꎃ": [],
    "ꎄ": [],
    "ꎅ": [],
    "ꎆ": [],
    "ꎇ": [],
    "ꎈ": [],
    "ꎉ": [],
    "ꎊ": [],
    "ꎋ": [],
    "ꎌ": [],
    "ꎍ": [],
    "ꎎ": [],
    "ꎏ": [],
    "ꎐ": [],
    "ꎑ": [],
    "ꎒ": [],
    "ꎓ": [],
    "ꎔ": [],
    "ꎕ": [],
    "ꎖ": [],
    "ꎗ": [],
    "ꎘ": [],
    "ꎙ": [],
    "ꎚ": [],
    "ꎛ": [],
    "ꎜ": [],
    "ꎝ": [],
    "ꎞ": [],
    "ꎟ": [],
    "ꎠ": [],
    "ꎡ": [],
    "ꎢ": [],
    "ꎣ": [],
    "ꎤ": [],
    "ꎥ": [],
    "ꎦ": [],
    "ꎧ": [],
    "ꎨ": [],
    "ꎩ": [],
    "ꎪ": [],
    "ꎫ": [],
    "ꎬ": [],
    "ꎭ": [],
    "ꎮ": [],
    "ꎯ": [],
    "ꎰ": [],
    "ꎱ": [],
    "ꎲ": [],
    "ꎳ": [],
    "ꎴ": [],
    "ꎵ": [],
    "ꎶ": [],
    "ꎷ": [],
    "ꎸ": [],
    "ꎹ": [],
    "ꎺ": [],
    "ꎻ": [],
    "ꎼ": [],
    "ꎽ": [],
    "ꎾ": [],
    "ꎿ": [],
    "ꏀ": [],
    "ꏁ": [],
    "ꏂ": [],
    "ꏃ": [],
    "ꏄ": [],
    "ꏅ": [],
    "ꏆ": [],
    "ꏇ": [],
    "ꏈ": [],
    "ꏉ": [],
    "ꏊ": [],
    "ꏋ": [],
    "ꏌ": [],
    "ꏍ": [],
    "ꏎ": [],
    "ꏏ": [],
    "ꏐ": [],
    "ꏑ": [],
    "ꏒ": [],
    "ꏓ": [],
    "ꏔ": [],
    "ꏕ": [],
    "ꏖ": [],
    "ꏗ": [],
    "ꏘ": [],
    "ꏙ": [],
    "ꏚ": [],
    "ꏛ": [],
    "ꏜ": [],
    "ꏝ": [],
    "ꏞ": [],
    "ꏟ": [],
    "ꏠ": [],
    "ꏡ": [],
    "ꏢ": [],
    "ꏣ": [],
    "ꏤ": [],
    "ꏥ": [],
    "ꏦ": [],
    "ꏧ": [],
    "ꏨ": [],
    "ꏩ": [],
    "ꏪ": [],
    "ꏫ": [],
    "ꏬ": [],
    "ꏭ": [],
    "ꏮ": [],
    "ꏯ": [],
    "ꏰ": [],
    "ꏱ": [],
    "ꏲ": [],
    "ꏳ": [],
    "ꏴ": [],
    "ꏵ": [],
    "ꏶ": [],
    "ꏷ": [],
    "ꏸ": [],
    "ꏹ": [],
    "ꏺ": [],
    "ꏻ": [],
    "ꏼ": [],
    "ꏽ": [],
    "ꏾ": [],
    "ꏿ": [],
    "ꐀ": [],
    "ꐁ": [],
    "ꐂ": [],
    "ꐃ": [],
    "ꐄ": [],
    "ꐅ": [],
    "ꐆ": [],
    "ꐇ": [],
    "ꐈ": [],
    "ꐉ": [],
    "ꐊ": [],
    "ꐋ": [],
    "ꐌ": [],
    "ꐍ": [],
    "ꐎ": [],
    "ꐏ": [],
    "ꐐ": [],
    "ꐑ": [],
    "ꐒ": [],
    "ꐓ": [],
    "ꐔ": [],
    "ꐕ": [],
    "ꐖ": [],
    "ꐗ": [],
    "ꐘ": [],
    "ꐙ": [],
    "ꐚ": [],
    "ꐛ": [],
    "ꐜ": [],
    "ꐝ": [],
    "ꐞ": [],
    "ꐟ": [],
    "ꐠ": [],
    "ꐡ": [],
    "ꐢ": [],
    "ꐣ": [],
    "ꐤ": [],
    "ꐥ": [],
    "ꐦ": [],
    "ꐧ": [],
    "ꐨ": [],
    "ꐩ": [],
    "ꐪ": [],
    "ꐫ": [],
    "ꐬ": [],
    "ꐭ": [],
    "ꐮ": [],
    "ꐯ": [],
    "ꐰ": [],
    "ꐱ": [],
    "ꐲ": [],
    "ꐳ": [],
    "ꐴ": [],
    "ꐵ": [],
    "ꐶ": [],
    "ꐷ": [],
    "ꐸ": [],
    "ꐹ": [],
    "ꐺ": [],
    "ꐻ": [],
    "ꐼ": [],
    "ꐽ": [],
    "ꐾ": [],
    "ꐿ": [],
    "ꑀ": [],
    "ꑁ": [],
    "ꑂ": [],
    "ꑃ": [],
    "ꑄ": [],
    "ꑅ": [],
    "ꑆ": [],
    "ꑇ": [],
    "ꑈ": [],
    "ꑉ": [],
    "ꑊ": [],
    "ꑋ": [],
    "ꑌ": [],
    "ꑍ": [],
    "ꑎ": [],
    "ꑏ": [],
    "ꑐ": [],
    "ꑑ": [],
    "ꑒ": [],
    "ꑓ": [],
    "ꑔ": [],
    "ꑕ": [],
    "ꑖ": [],
    "ꑗ": [],
    "ꑘ": [],
    "ꑙ": [],
    "ꑚ": [],
    "ꑛ": [],
    "ꑜ": [],
    "ꑝ": [],
    "ꑞ": [],
    "ꑟ": [],
    "ꑠ": [],
    "ꑡ": [],
    "ꑢ": [],
    "ꑣ": [],
    "ꑤ": [],
    "ꑥ": [],
    "ꑦ": [],
    "ꑧ": [],
    "ꑨ": [],
    "ꑩ": [],
    "ꑪ": [],
    "ꑫ": [],
    "ꑬ": [],
    "ꑭ": [],
    "ꑮ": [],
    "ꑯ": [],
    "ꑰ": [],
    "ꑱ": [],
    "ꑲ": [],
    "ꑳ": [],
    "ꑴ": [],
    "ꑵ": [],
    "ꑶ": [],
    "ꑷ": [],
    "ꑸ": [],
    "ꑹ": [],
    "ꑺ": [],
    "ꑻ": [],
    "ꑼ": [],
    "ꑽ": [],
    "ꑾ": [],
    "ꑿ": [],
    "ꒀ": [],
    "ꒁ": [],
    "ꒂ": [],
    "ꒃ": [],
    "ꒄ": [],
    "ꒅ": [],
    "ꒆ": [],
    "ꒇ": [],
    "ꒈ": [],
    "ꒉ": [],
    "ꒊ": [],
    "ꒋ": [],
    "ꒌ": [],
    // BELOW ARE RADICALS
    "꒐": [],
    "꒑": [],
    "꒒": [],
    "꒓": [],
    "꒔": [],
    "꒕": [],
    "꒖": [],
    "꒗": [],
    "꒘": [],
    "꒙": [],
    "꒚": [],
    "꒛": [],
    "꒜": [],
    "꒝": [],
    "꒞": [],
    "꒟": [],
    "꒠": [],
    "꒡": [],
    "꒢": [],
    "꒣": [],
    "꒤": [],
    "꒥": [],
    "꒦": [],
    "꒧": [],
    "꒨": [],
    "꒩": [],
    "꒪": [],
    "꒫": [],
    "꒬": [],
    "꒭": [],
    "꒮": [],
    "꒯": [],
    "꒰": [],
    "꒱": [],
    "꒲": [],
    "꒳": [],
    "꒴": [],
    "꒵": [],
    "꒶": [],
    "꒷": [],
    "꒸": [],
    "꒹": [],
    "꒺": [],
    "꒻": [],
    "꒼": [],
    "꒽": [],
    "꒾": [],
    "꒿": [],
    "꓀": [],
    "꓁": [],
    "꓂": [],
    "꓃": [],
    "꓄": [],
    "꓅": [],
    "꓆": [],
};

if (Object.values(charStrokes).flat().some(x => !(x in strokeExpansionRules))) {
    console.error("Non-symbol used in charStrokes definition! at:\n" +
        Object.entries(charStrokes)
            .filter(([, strokes]) => strokes.some(s => !(s in strokeExpansionRules)))
            .map(([key, value]) => [key, 
                value.filter(v => !(v in strokeExpansionRules))])
            .map(([key, value]) => `${value.map(s => "'" + s + "'").join(', ')} in ${key}`)
            .join('\n'));
}

const charStrokesExpanded = (function() {
    const memo = new Map();
    return Object.fromEntries(Object.entries(charStrokes)
        .map(([k, v]) => [k, expandStrokes(arrToCountObj(v), memo)]));
})();

/**
 * @type {Object.<string, Object<number, Set<string>>>}
 */
const charStrokesLookupReverse = {};

Object.entries(charStrokesExpanded).forEach(([char, countObjs]) => {
    countObjs.forEach(countObj => {
        Object.entries(countObj).forEach(([stroke, count]) => {
            if (!charStrokesLookupReverse[stroke]) {
                charStrokesLookupReverse[stroke] = {}
            }
            for (let i = 1; i <= count; ++i) {
                if (!charStrokesLookupReverse[stroke][i]) {
                    charStrokesLookupReverse[stroke][i] = new Set();
                }
                charStrokesLookupReverse[stroke][i].add(char);
            }
        });
    });
});

/**
 * 
 * @param {string[]} strokes
 * @returns {[string, bool][]}
 */
function resolveCharsFromStrokes(strokes) {
    const countObj = arrToCountObj(strokes);

    const sets = Object.entries(countObj)
        .map(([stroke, count]) =>
            charStrokesLookupReverse[stroke] &&
            charStrokesLookupReverse[stroke][count]);
    if (sets.length === 0 || sets.includes(undefined)) return [];

    const setsSorted = sets.sort((set1, set2) => set1.size - set2.size);
    const candidates = new Set(setsSorted[0]);

    for (const set of sets.slice(1)) {
        candidates.forEach(candidate => {
            if (!set.has(candidate)) {
                candidates.delete(candidate);
            }
        });
    }

    const ret = [];

    for (const candidate of candidates) {
        const expansions = charStrokesExpanded[candidate];
        let match = false;
        let exact = false;
        for (const expansion of expansions) {
            if (Object.keys(expansion).length < Object.keys(countObj).length) 
                continue;

            let expansionMatch = Object.keys(countObj)
                .every(key => key in expansion);
            let expansionExact = expansionMatch && Object.entries(expansion)
                .every(([key, value]) => key in countObj &&
                    countObj[key] === value);

            if (expansionMatch) match = true;
            if (expansionExact) {
                exact = true;
                break;
            }
        }
        if (match) ret.push([candidate, exact]);
    }

    return ret;
}

document.addEventListener('DOMContentLoaded', () => {
    if (typeof charInfo === 'undefined') {
        alert(t('load_error'));
        return;
    }

    let currentStrokes = "";

    const strokeKeyboard = document.getElementById('stroke-keyboard');
    const strokeInputDisplay = document.getElementById('stroke-input-display');
    const strokeCharContainer = document.getElementById('stroke-char-buttons');
    const matchCountLabel = document.getElementById('match-count');
    const clearStrokeBtn = document.getElementById('clear-stroke-btn');

    function initStrokeKeyboard() {
        inputtableStrokes.forEach(stroke => {
            const btn = document.createElement('button');
            btn.textContent = stroke;
            btn.className = 'stroke-key-btn';
            btn.dataset.stroke = stroke;

            btn.addEventListener('click', () => {
                addStroke(stroke);
            });

            strokeKeyboard.appendChild(btn);
        });
    }

    function addStroke(stroke) {
        let strokeArray = currentStrokes.split('');
        strokeArray.push(stroke);
        strokeArray.sort();
        currentStrokes = strokeArray.join('');

        updateStrokeUI();
        filterCharsByStrokes();
    }

    function clearStrokes() {
        currentStrokes = "";
        updateStrokeUI();
        filterCharsByStrokes();
    }

    function updateStrokeUI() {
        strokeInputDisplay.textContent = currentStrokes;
        if (currentStrokes.length > 0) {
            strokeInputDisplay.style.backgroundColor = "#eef2ff";
        } else {
            strokeInputDisplay.style.backgroundColor = "#fff";
        }
    }

    function filterCharsByStrokes() {
        strokeCharContainer.innerHTML = '';

        if (currentStrokes.length === 0) {
            strokeCharContainer.innerHTML = `<p class="hint">${t('stroke_hint')}</p>`;
            matchCountLabel.textContent = '0';
            return;
        }

        const inputStrokes = currentStrokes;
        const matchedChars = resolveCharsFromStrokes(currentStrokes);

        matchCountLabel.textContent = matchedChars.length;

        if (matchedChars.length === 0) {
            strokeCharContainer.innerHTML = `<p class="hint">${t('stroke_no_match')}</p>`;
        } else {
            matchedChars.forEach(([char, exact]) => {
                const btn = createCharButton(char, exact);
                if (btn) strokeCharContainer.appendChild(btn);
            });
        }
    }

    document.addEventListener('keydown', (e) => {
        if (!document.getElementById('panel-stroke').classList.contains('active')) return;
        if (e.ctrlKey || e.altKey || e.metaKey) return;

        const key = e.key.toUpperCase();
        if (inputtableStrokes.has(key)) {
            e.preventDefault();
            addStroke(key);
        } else if (e.key === 'Escape') {
            clearStrokes();
        }
    });

    clearStrokeBtn.addEventListener('click', clearStrokes);

    initStrokeKeyboard();
});
